// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Cart struct {
	ID         int64     `json:"id"`
	UserID     int32     `json:"user_id"`
	MerchantID int32     `json:"merchant_id"`
	ProductID  int32     `json:"product_id"`
	Qty        int32     `json:"qty"`
	TotalPrice int32     `json:"total_price"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Category struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Merchant struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Lat       string    `json:"lat"`
	Long      string    `json:"long"`
	Logo      string    `json:"logo"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Product struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	Price      int32     `json:"price"`
	CategoryID int32     `json:"category_id"`
	MerchantID int32     `json:"merchant_id"`
	Image      string    `json:"image"`
	Stock      int32     `json:"stock"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Password  string    `json:"password"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
